AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ConstructApi:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2023
      Handler: bootstrap
      CodeUri: .
      Architectures:
        - x86_64
      Environment:
        Variables:
          JWT_SECRET: secret
          REPOSITORY_DRIVER: dynamodb
          DYNAMODB_TABLE: construct-main-app
          MP_SUCCESS_URL: http://localhost:5173/dashboard
          MP_FAILURE_URL: http://localhost:5173/checkout
          GOOGLE_CLIENT_ID: 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
          AUDIENCE: 74915047275-n1i484h8kiu987e5jt8r8bem47pe2jt6.apps.googleusercontent.com
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
